// import {
// 	StyledInput,
// 	StyledTextArea,
// 	StyledSelect,
// } from '../components/molecules/LoginForm/LoginForm.styles.ts';
// import { showNextPortfolioInput, showNextProjectInput } from '../utils/showNextInput.ts';
//
// export const STUDENT_FORM_VALUES = [
// 	{
// 		label: 'E-mail*',
// 		name: 'email',
// 		controlName: 'email',
// 		type: 'email',
// 		defaultValue: userData ? userData.email ?? '' : '',
// 		component: StyledInput,
// 	},
// 	{
// 		label: 'Numer telefonu',
// 		name: 'tel',
// 		controlName: 'tel',
// 		type: 'tel',
// 		defaultValue: userData ? userData.tel ?? '' : '',
// 		component: StyledInput,
// 	},
// 	{
// 		label: 'Imię*',
// 		name: 'firstName',
// 		controlName: 'firstName',
// 		type: 'text',
// 		defaultValue: userData?.firstName ?? '',
// 		component: StyledInput,
// 	},
// 	{
// 		label: 'Nazwisko*',
// 		name: 'lastName',
// 		controlName: 'lastName',
// 		type: 'text',
// 		defaultValue: userData ? userData.lastName : '',
// 		component: StyledInput,
// 	},
// 	{
// 		label: 'Login GitHuba',
// 		name: 'gitHubUserName',
// 		controlName: 'gitHubUserName',
// 		type: 'text',
// 		defaultValue: userData ? userData.gitHubUserName ?? '' : '',
// 		component: StyledInput,
// 	},
// 	{
// 		label: 'Linki do portfolio',
// 		subFields: [
// 			{
// 				name: 'portfolioUrl1',
// 				controlName: 'portfolioUrl1',
// 				type: 'text',
// 				defaultValue: userData ? userData.portfolioUrls[0]?.portfolioUrl : '',
// 				component: StyledInput,
// 				onChange: (e) => showNextPortfolioInput({ e, setIsPortfolioInputHidden }),
// 			},
// 			{
// 				name: 'portfolioUrl2',
// 				controlName: 'portfolioUrl2',
// 				type: 'url',
// 				defaultValue: userData ? userData.portfolioUrls[1]?.portfolioUrl : '',
// 				component: StyledInput,
// 				onChange: (e) => showNextPortfolioInput({ e, setIsPortfolioInputHidden }),
// 			},
// 			{
// 				name: 'portfolioUrl3',
// 				controlName: 'portfolioUrl3',
// 				type: 'url',
// 				defaultValue: userData ? userData.portfolioUrls[2]?.portfolioUrl : '',
// 				component: StyledInput,
// 				onChange: (e) => showNextPortfolioInput({ e, setIsPortfolioInputHidden }),
// 			},
// 			{
// 				name: 'portfolioUrl4',
// 				controlName: 'portfolioUrl4',
// 				type: 'url',
// 				defaultValue: userData ? userData.portfolioUrls[3]?.portfolioUrl : '',
// 				component: StyledInput,
// 				onChange: (e) => showNextPortfolioInput({ e, setIsPortfolioInputHidden }),
// 			},
// 		],
// 	},
// 	{
// 		label: 'Linki do projektu zaliczeniowego',
// 		subFields: [
// 			{
// 				name: 'projectUrl1',
// 				controlName: 'projectUrl1',
// 				type: 'url',
// 				defaultValue: userData ? userData.projectUrls[0]?.projectUrl : '',
// 				component: StyledInput,
// 				onChange: (e) => showNextProjectInput({ e, setIsProjectInputHidden }),
// 			},
// 			{
// 				name: 'projectUrl2',
// 				controlName: 'projectUrl2',
// 				type: 'url',
// 				defaultValue: userData ? userData.projectUrls[1]?.projectUrl : '',
// 				component: StyledInput,
// 				onChange: (e) => showNextProjectInput({ e, setIsProjectInputHidden }),
// 			},
// 			{
// 				name: 'projectUrl3',
// 				controlName: 'projectUrl3',
// 				type: 'url',
// 				defaultValue: userData ? userData.projectUrls[2]?.projectUrl : '',
// 				component: StyledInput,
// 				onChange: (e) => showNextProjectInput({ e, setIsProjectInputHidden }),
// 			},
// 		],
// 	},
// 	{
// 		label: 'Bio',
// 		name: 'bio',
// 		controlName: 'bio',
// 		type: 'textarea',
// 		defaultValue: userData?.bio || '',
// 		component: StyledTextArea,
// 	},
// 	{
// 		label: 'Preferowane miejsce pracy',
// 		name: 'expectedTypeWork',
// 		controlName: 'expectedTypeWork',
// 		type: 'select',
// 		defaultValue: userData ? userData.expectedTypeWork : 'Bez znaczenia',
// 		options: [
// 			{ value: expectedTypeWorkEnum.LOCAL, label: 'Na miejscu' },
// 			{ value: expectedTypeWorkEnum.FLEXIBLE, label: 'Gotowość do przeprowadzki' },
// 			{ value: expectedTypeWorkEnum.REMOTE, label: 'Wyłącznie zdalnie' },
// 			{ value: expectedTypeWorkEnum.HYBRID, label: 'Hybrydowo' },
// 			{ value: expectedTypeWorkEnum.NOT_IMPORTANT, label: 'Bez znaczenia' },
// 		],
// 		component: StyledSelect,
// 	},
// 	{
// 		label: 'Miasto docelowe, gdzie chciałbyś/chciałabyś pracować',
// 		name: 'targetWorkCity',
// 		controlName: 'targetWorkCity',
// 		type: 'text',
// 		defaultValue: userData ? userData.targetWorkCity ?? '' : '',
// 		component: StyledInput,
// 	},
// 	{
// 		label: 'Oczekiwany typ kontraktu',
// 		name: 'expectedContractType',
// 		controlName: 'expectedContractType',
// 		type: 'select',
// 		defaultValue: userData ? userData.expectedContractType : 'Brak preferencji',
// 		options: [
// 			{ value: expectedContractTypeEnum.UOP, label: 'Tylko UoP' },
// 			{ value: expectedContractTypeEnum.B2B, label: 'Możliwe B2B' },
// 			{ value: expectedContractTypeEnum.UZ_UOD, label: 'Możliwe UZ/UoD' },
// 			{ value: expectedContractTypeEnum.NOT_IMPORTANT, label: 'Brak preferencji' },
// 		],
// 		component: StyledSelect,
// 	},
// 	{
// 		label: 'Oczekiwane wynagrodzenie miesięczne netto (zł)',
// 		name: 'expectedSalary',
// 		controlName: 'expectedSalary',
// 		type: 'number',
// 		defaultValue: userData ? userData.expectedSalary ?? '' : '',
// 		component: StyledInput,
// 	},
// 	{
// 		label: 'Czy wyrażasz zgodę na odbycie bezpłatnych praktyk/stażu na początek?',
// 		name: 'canTakeApprenticeship',
// 		controlName: 'canTakeApprenticeship',
// 		type: 'select',
// 		defaultValue: userData ? userData.canTakeApprenticeship : 'nie',
// 		options: [
// 			{ value: canTakeApprenticeshipEnum.YES, label: 'Tak' },
// 			{ value: canTakeApprenticeshipEnum.NO, label: 'Nie' },
// 		],
// 		component: StyledSelect,
// 	},
// 	{
// 		label: 'Ilość miesięcy doświadczenia komercyjnego w programowaniu',
// 		name: 'monthsOfCommercialExp',
// 		controlName: 'monthsOfCommercialExp',
// 		type: 'number',
// 		defaultValue: userData ? userData.monthsOfCommercialExp ?? 0 : 0,
// 		component: StyledInput,
// 	},
// 	{
// 		label: 'Przebieg edukacji',
// 		name: 'education',
// 		controlName: 'education',
// 		type: 'textarea',
// 		defaultValue: userData ? userData.education ?? '' : '',
// 		component: StyledTextArea,
// 	},
// 	{
// 		label: 'Przebieg doświadczenia zawodowego',
// 		name: 'workExperience',
// 		controlName: 'workExperience',
// 		type: 'textarea',
// 		defaultValue: userData ? userData.workExperience ?? '' : '',
// 		component: StyledTextArea,
// 	},
// 	{
// 		label: 'Kursy i certyfikaty związane z programowaniem',
// 		name: 'courses',
// 		controlName: 'courses',
// 		type: 'textarea',
// 		defaultValue: userData ? userData.courses ?? '' : '',
// 		component: StyledTextArea,
// 	},
// ];
